/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'appointmentTime' : Time,
  'appointmentType' : AppointmentType,
  'patientRecordNumber' : string,
  'doctorName' : string,
}
export type AppointmentType = { 'checkUp' : null } |
  { 'emergency' : null } |
  { 'followUp' : null } |
  { 'consultation' : null };
export interface Doctor {
  'contactInfo' : string,
  'name' : string,
  'specialty' : string,
}
export interface Patient {
  'contactInfo' : string,
  'name' : string,
  'medicalRecordNumber' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'specialty' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitNote {
  'visitTime' : Time,
  'diagnosis' : string,
  'notes' : string,
  'appointmentId' : string,
  'prescriptions' : Array<string>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDoctor' : ActorMethod<[string, string, string], undefined>,
  'addVisitNote' : ActorMethod<
    [string, string, string, string, Array<string>, Time],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelAppointment' : ActorMethod<[string], undefined>,
  'getAllDoctors' : ActorMethod<[], Array<Doctor>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAppointmentsForPatient' : ActorMethod<[string], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPatient' : ActorMethod<[string], [] | [Patient]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitNotes' : ActorMethod<[string], Array<VisitNote>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerPatient' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleAppointment' : ActorMethod<
    [string, string, Time, AppointmentType],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];