/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Doctor = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'specialty' : IDL.Text,
});
export const Patient = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'medicalRecordNumber' : IDL.Text,
});
export const AppointmentType = IDL.Variant({
  'checkUp' : IDL.Null,
  'emergency' : IDL.Null,
  'followUp' : IDL.Null,
  'consultation' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'appointmentTime' : Time,
  'appointmentType' : AppointmentType,
  'patientRecordNumber' : IDL.Text,
  'doctorName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'specialty' : IDL.Opt(IDL.Text),
});
export const VisitNote = IDL.Record({
  'visitTime' : Time,
  'diagnosis' : IDL.Text,
  'notes' : IDL.Text,
  'appointmentId' : IDL.Text,
  'prescriptions' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDoctor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addVisitNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), Time],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelAppointment' : IDL.Func([IDL.Text], [], []),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAppointmentsForPatient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPatient' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitNotes' : IDL.Func([IDL.Text], [IDL.Vec(VisitNote)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerPatient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, Time, AppointmentType],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Doctor = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'specialty' : IDL.Text,
  });
  const Patient = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'medicalRecordNumber' : IDL.Text,
  });
  const AppointmentType = IDL.Variant({
    'checkUp' : IDL.Null,
    'emergency' : IDL.Null,
    'followUp' : IDL.Null,
    'consultation' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'appointmentTime' : Time,
    'appointmentType' : AppointmentType,
    'patientRecordNumber' : IDL.Text,
    'doctorName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'specialty' : IDL.Opt(IDL.Text),
  });
  const VisitNote = IDL.Record({
    'visitTime' : Time,
    'diagnosis' : IDL.Text,
    'notes' : IDL.Text,
    'appointmentId' : IDL.Text,
    'prescriptions' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDoctor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addVisitNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), Time],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelAppointment' : IDL.Func([IDL.Text], [], []),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAppointmentsForPatient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPatient' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitNotes' : IDL.Func([IDL.Text], [IDL.Vec(VisitNote)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerPatient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, Time, AppointmentType],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };